### ISSUE TITLE
Truecaser Save to File

### ISSUE THREAD

**Issue by Patdue** [alvations/sacremoses#15]
Saving a previously trained model like shown in the readme does not work.
```python
mtr = MosesTruecaser()
mtr.train('big.txt')  # should be mtr.train_from_file('big.txt')?
mtr._save_model('big.truecasemodel')
```

**Comment by alvations** [comment]
Ah, I should have refreshed the readme =)

Ein moment.

**Comment by Patdue** [comment]
Awesome, i'll try it out, thanks!

**Comment by KonceptBlast** [comment]
Is it possible to store truecase model not in file but as a variable in python?

**Comment by alvations** [comment]
@KonceptBlast yes the `.save()` interface would save the file, e.g.

```
>>> from sacremoses import MosesTruecaser, MosesTokenizer

# Train a new truecaser from a 'big.txt' file.
>>> mtr = MosesTruecaser()
>>> mtok = MosesTokenizer(lang='en')

# Save the truecase model to 'big.truecasemodel' using `save_to`
>> tokenized_docs = [mtok.tokenize(line) for line in open('big.txt')]
>>> mtr.train(tokenized_docs, save_to='big.truecasemodel')
``

And to load the model:

```
# Loads a model and truecase a string using trained model.
>>> mtr = MosesTruecaser('big.truecasemodel')

```

**Comment by KonceptBlast** [comment]
Yes, thank you @alvations for your reply.
However I wanted to know if it is possible to first train the truecase model and apply it on-the-fly (without saving a truecase model to a file)
Is it mean I should make relevant changes in the code and modify `_save_model_from_casing(self,` casing, filename)` so that it returns an truecase model object instead of saving the output to the file?
